name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: autoscaler
      run: docker build . --file autoscaler/Dockerfile --tag autoscaller:1.0.0
