name: Docker Image CI

on:
  workflow_dispatch:
    branches: [ "main" ]
      #  push:
      #branches: [ "main" ]
      # pull_request:
      #branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build serving-webhook
      run: docker build . --file knative/webhook/Dockerfile --tag webhook:1.0.0 
    - name: push werving-webhook image
      run: docker tag webhook:1.0.0 registry.cn-hangzhou.aliyuncs.com/code_night/knative-webhook:1.0.0 && docker login registry.cn-hangzhou.aliyuncs.com --username=code_night --password=${{ secrets.PASSWORD }} && docker push registry.cn-hangzhou.aliyuncs.com/code_night/knative-webhook:1.0.0
   

    - name: build event-controller
      run: docker build . --file knative/event-controller/Dockerfile --tag knative-event-controller:1.0.0
    - name: push event-controller image
      run: docker tag webhook:1.0.0 registry.cn-hangzhou.aliyuncs.com/code_night/knative-event-controller:1.0.0 && docker push registry.cn-hangzhou.aliyuncs.com/code_night/knative-event-controller:1.0.0
 
    - name: build event-webhook
      run: docker build . --file knative/event-webhook/Dockerfile --tag knative-event-webhook:1.0.0 
    - name: push event-webhook image
      run: docker tag webhook:1.0.0 registry.cn-hangzhou.aliyuncs.com/code_night/knative-event-controller:1.0.0 && docker push registry.cn-hangzhou.aliyuncs.com/code_night/knative-event-webhook:1.0.0
